window.ENV = {
    LAUNCHDARKLYCLIENTID: $env.LAUNCHDARKLYCLIENTID,
    LAUNCHDARKLYENVIRONMENTNAME: $env.LAUNCHDARKLYENVIRONMENTNAME,
    LOCALYTICS_APP_KEY: $env.LOCALYTICS_APP_KEY,
    DEPENDENT_SERVICE_BASE_URL: $env.DEPENDENT_SERVICE_BASE_URL
  };